"use client"

// components/save-card.tsx
// Displays a single saved URL as a card with its OG metadata.
// Shows: image, title, URL, source badge, and a delete button on hover.

import { Card, CardContent } from "@/components/ui/card";
import { ExternalLink, Globe, Trash2 } from "lucide-react";
import type { Save } from "@/types/save";
import { Button } from "@/components/ui/button";
import { deleteSave } from "@/lib/actions/delete-save";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel,
  AlertDialogContent, AlertDialogDescription, AlertDialogFooter,
  AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

type SaveCardProps = {
  save: Save;
};

export function SaveCard({ save }: SaveCardProps) {
  // Format the URL for display — strip protocol and trailing slash
  // e.g. "https://www.example.com/article/" becomes "www.example.com/article"
  const displayUrl = save.url
    .replace(/^https?:\/\//, "")
    .replace(/\/$/, "");

  return (
    <Card className="group relative overflow-hidden rounded-xl border-border/50 transition-colors hover:border-border">
      {/* Delete button — only visible on hover, opens confirmation dialog */}
      <AlertDialog>
        <AlertDialogTrigger asChild>
          <Button
            variant="ghost"
            size="icon"
            className="absolute top-2 right-2 z-10 opacity-0 group-hover:opacity-100 transition-opacity bg-background/80 hover:bg-destructive hover:text-destructive-foreground"
          >
            <Trash2 className="size-4" />
          </Button>
        </AlertDialogTrigger>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this save?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={async () => {
                await deleteSave(save.id);
              }}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <a
        href={save.url}
        target="_blank"
        rel="noopener noreferrer"
        className="block"
      >
        {/* OG image — only render if we have one */}
        {save.image_url && (
          <div className="relative h-40 w-full overflow-hidden bg-muted">
            {/*
              Using a plain <img> instead of next/image here because OG images
              come from any domain. next/image requires configuring remotePatterns
              for every possible domain, which is impractical for a bookmark app.
              We'll optimize this later if needed.
            */}
            <img
              src={save.image_url}
              alt={save.title || "Saved link preview"}
              className="h-full w-full object-cover"
            />
          </div>
        )}

        <CardContent className="space-y-2 p-4">
          {/* Category badge — AI-generated label like "Entertainment", "Technology" */}
          {save.category && (
            <span className="rounded-full bg-amber-500/15 text-amber-400 text-xs font-medium px-2.5 py-0.5">
          {save.category}
            </span>
          )}
          {/* Title — falls back to the URL if no OG title was found */}
          <h3 className="font-semibold text-base leading-snug line-clamp-2">
            {save.title || displayUrl}
          </h3>
          {/* AI summary — 2-line max description generated by Gemini */}
          {save.summary && (
          <p className="text-sm text-muted-foreground/80 line-clamp-2 leading-relaxed">
            {save.summary}
          </p>
          )}
          {/* URL preview — truncated with ellipsis if too long */}
          <p className="text-sm text-muted-foreground truncate flex items-center gap-1.5">
            <ExternalLink className="size-3 shrink-0" />
            {displayUrl}
          </p>
          {/* Source type badge — e.g. "YouTube", "GitHub" */}
          {/* Only shows if OG metadata included a site name */}
          {save.source_type && (
            <span className="inline-flex items-center gap-1 rounded-md bg-muted px-2 py-0.5 text-xs text-muted-foreground">
              <Globe className="size-3" />
              {save.source_type}
            </span>
          )}
            {/* Tags — AI-generated keywords shown as hashtag pills */}
            {save.tags && save.tags.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
                {save.tags.map((tag) => (
                    <span key={tag} className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">
                        #{tag}
                    </span>
                ))}
            </div>
            )}
        </CardContent>
      </a>
    </Card>
  );
}
